// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// d2r_fsigma_2
SEXP d2r_fsigma_2(SEXP input, SEXP date_col, SEXP obs_col, SEXP what, SEXP extra_vars, SEXP eps, SEXP itt_max);
RcppExport SEXP _Dipol2Red_d2r_fsigma_2(SEXP inputSEXP, SEXP date_colSEXP, SEXP obs_colSEXP, SEXP whatSEXP, SEXP extra_varsSEXP, SEXP epsSEXP, SEXP itt_maxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type input(inputSEXP);
    Rcpp::traits::input_parameter< SEXP >::type date_col(date_colSEXP);
    Rcpp::traits::input_parameter< SEXP >::type obs_col(obs_colSEXP);
    Rcpp::traits::input_parameter< SEXP >::type what(whatSEXP);
    Rcpp::traits::input_parameter< SEXP >::type extra_vars(extra_varsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type itt_max(itt_maxSEXP);
    rcpp_result_gen = Rcpp::wrap(d2r_fsigma_2(input, date_col, obs_col, what, extra_vars, eps, itt_max));
    return rcpp_result_gen;
END_RCPP
}
// d2r_correct_pol
SEXP d2r_correct_pol(SEXP data, SEXP px_corr, SEXP py_corr, SEXP angle_corr);
RcppExport SEXP _Dipol2Red_d2r_correct_pol(SEXP dataSEXP, SEXP px_corrSEXP, SEXP py_corrSEXP, SEXP angle_corrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type data(dataSEXP);
    Rcpp::traits::input_parameter< SEXP >::type px_corr(px_corrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type py_corr(py_corrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type angle_corr(angle_corrSEXP);
    rcpp_result_gen = Rcpp::wrap(d2r_correct_pol(data, px_corr, py_corr, angle_corr));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_Dipol2Red_d2r_fsigma_2", (DL_FUNC) &_Dipol2Red_d2r_fsigma_2, 7},
    {"_Dipol2Red_d2r_correct_pol", (DL_FUNC) &_Dipol2Red_d2r_correct_pol, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_Dipol2Red(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
