# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

d2r_fsigma_2 <- function(input, date_col, obs_col, what, extra_vars, eps, itt_max) {
    .Call('_Dipol2Red_d2r_fsigma_2', PACKAGE = 'Dipol2Red', input, date_col, obs_col, what, extra_vars, eps, itt_max)
}

d2r_correct_pol <- function(data, px_corr, py_corr, angle_corr) {
    .Call('_Dipol2Red_d2r_correct_pol', PACKAGE = 'Dipol2Red', data, px_corr, py_corr, angle_corr)
}

